name: 'fire_incidents'

config-version: 2
version: '0.1'

profile: 'fire-incident-test'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  fire_incidents:
    aggregated_incidents:
      materialized: table